stages:
  - test
  - build
  - upload

linter:
  image: tarantool/tarantool:1.10.8
  stage: test
  script:
      - luarocks install https://raw.githubusercontent.com/tarantool/luacheck/master/luacheck-scm-1.rockspec
      - luacheck .
prebuild:
  stage: test
  script:
    - git describe --long
    - git clone --recurse-submodules https://github.com/packpack/packpack.git packpack
  artifacts:
    paths:
      - packpack/

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    OS: centos
    DIST: 7
    PRODUCT: tarantool-switchover
  script:
    - packpack/packpack
  artifacts:
    paths:
      - build/

upload:
  stage: upload
  script:
    - export PKG_VERSION="$(git describe --tags | sed -e 's/-/./g' -e 's/\.[^\.]*$//g')"
    - 'cd build; for f in *.rpm; do curl -v -s -H "JOB-TOKEN: $CI_JOB_TOKEN" -T "$f" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/switchover/${PKG_VERSION}/$f"; done'
  only:
    - ci
    - master
